[versions]
activity-ktx = "1.12.2"
android-gradle-plugin = "8.13.2"
appcompat = "1.7.1"
camera = "1.5.2"
core-ktx = "1.17.0"
jgit = "7.5.0.202512021534-r"
fragment-ktx = "1.8.9"
kotlin = "2.3.0"
material = "1.13.0"
preference-ktx = "1.2.1"
zxing = "3.5.4"

[libraries]
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
